name: "Setup Monitoring"
Description: "This action deploy monitoring stacks for poseidonos"
inputs:
  POS_WORKING_DIR
    required: true
  GA_COMMIT_HASH
    required: true
  GA_WORKFLOW
    required: true
  GA_DETAIL
    required: true

runs:
  using: "composite"
  steps:
    - run: echo ${{inputs.POS_WORKING_DIR}}
      shell: bash
    - run: echo ${{inputs.GA_COMMIT_HASH}}
      shell: bash
    - run: echo ${{inputs.GA_WORKFLOW}}
      shell: bash
    - run: echo ${{inputs.GA_DETAIL}}
      shell: bash


