name: "Setup Monitoring"
Description: "This action deploy monitoring stacks for poseidonos"
inputs:
  POS_WORKING_DIR:
    required: true
  GA_COMMIT_HASH:
    required: true
  GA_WORKFLOW:
    required: true
  GA_DETAIL:
    required: true
    
  POS_EXPORTER_PORT:
    required: true

  AMP_REMOTE_WRITE_URL:
    required: true
  AMP_SIGV4_REGION:
    required: true
  AMP_SIGV4_ACCESS_KEY:
    required: true
  AMP_SIGV4_SECRET_KEY:
    required: true
  
  LOGSTASH_PORT:									      
    required: true
  
  OS_DOMAIN_ENDPOINT:
    required: true
  OS_REGION:
    required: true
  
runs:
  using: "composite"
  steps:  
    - name: "Prometheus - config setting"
      shell: bash
      env:
        PROMETHEUS_CONF_PATH: ${{ inputs.POS_WORKING_DIR }}/config/prometheus.yml
        
        GA_COMMIT_HASH: ${{ inputs.GA_COMMIT_HASH }}
        GA_WORKFLOW: ${{ inputs.GA_WORKFLOW }}
        GA_DETAIL: ${{ inputs.GA_DETAIL }}
        
        AMP_SIGV4_REGION: ${{ inputs.AMP_SIGV4_REGION }}
        AMP_SIGV4_ACCESS_KEY: ${{ inputs.AMP_SIGV4_ACCESS_KEY }}
        AMP_SIGV4_SECRET_KEY: ${{ inputs.AMP_SIGV4_SECRET_KEY }}
      run: |
        my_str=$(cat << EOF
            scrape_config:
              abc:
              EOF
              )
        echo ${my_str}
