
name: C-Precommit_VM_Test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'

jobs:
  Build:
    runs-on: VM
    steps:
    
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Build Setup
      id: build_id
      working-directory: ${{github.workspace}}
      run: | 
        chmod +x .github/workflows/script/build_setup.sh
        .github/workflows/script/build_setup.sh -r ${{github.sha}} -d ${{github.workspace}} -c --with-fpic 
    
    - name: Upload POS Binaries
      if: ${{ steps.build_id.outcome == 'success' }} 
      uses: actions/upload-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

  IO_Exception_Test:
    needs: Build
    runs-on: VM
    steps:
    
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Test Setup
      working-directory: ${{github.workspace}}
      run: | 
        sudo script/pkgdep.sh
        sudo ./configure --with-fpic 
        cd lib; sudo cmake . -DSPDK_DEBUG_ENABLE=n -DUSE_LOCAL_REPO=n
        cd ${{github.workspace}}; sudo cp -f config/air_ci.cfg config/air.cfg
        sudo make CACHE=Y -j ${job_number} -C lib
        sudo mkdir bin
        sudo mkdir tool/cli/docs/manpage

    - name: Download POS Binaries
      uses: actions/download-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

    - name: change mode
      working-directory: ${{github.workspace}}
      run: |
          sudo chmod -R +x bin

    - name: POS setup
      working-directory: ${{github.workspace}}
      run: |
          sudo cp ./config/telemetry_default.yaml /etc/pos/telemetry_default.yaml;
          sudo install -m 755 bin/poseidonos /usr/local/bin
          sudo install -m 755 bin/poseidonos-cli /usr/local/bin
          sudo tool/udev/generate_udev_rule.sh
          sudo cp tool/udev/99-custom-nvme.rules /etc/udev/rules.d/99-custom-nvme.rules;
          sudo udevadm control --reload-rules && udevadm trigger;
          sudo ./script/setup_env.sh
          sudo cp config/ibofos_for_aws_vm_ci.conf /etc/pos/pos.conf
          sudo rmmod nvme_tcp
          sudo rmmod nvme_rdma
          sudo rmmod nvme_fabrics
          sudo modprobe nvme_tcp
          sudo modprobe nvme_rdma
          sudo modprobe nvme_fabrics

    - name: IO + Exception Simple
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/io_exception/io_exception.sh
        .github/workflows/script/io_exception/io_exception.sh ${{github.workspace}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: IO_Exception_LOG
        path: |
          /var/log/pos

  Normal_IO_NPOR_SPOR_Test:
    needs: Build
    runs-on: VM
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Test Setup
      working-directory: ${{github.workspace}}
      run: | 
        sudo script/pkgdep.sh
        sudo ./configure --with-fpic 
        cd lib; sudo cmake . -DSPDK_DEBUG_ENABLE=n -DUSE_LOCAL_REPO=n
        cd ${{github.workspace}}; sudo cp -f config/air_ci.cfg config/air.cfg
        sudo make CACHE=Y -j ${job_number} -C lib
        sudo mkdir bin
        sudo mkdir tool/cli/docs/manpage

    - name: Download POS Binaries
      uses: actions/download-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

    - name: change mode
      working-directory: ${{github.workspace}}
      run: |
          sudo chmod -R +x bin

    - name: POS setup
      working-directory: ${{github.workspace}}
      run: |
          sudo cp ./config/telemetry_default.yaml /etc/pos/telemetry_default.yaml;
          sudo install -m 755 bin/poseidonos /usr/local/bin
          sudo install -m 755 bin/poseidonos-cli /usr/local/bin
          sudo tool/udev/generate_udev_rule.sh
          sudo cp tool/udev/99-custom-nvme.rules /etc/udev/rules.d/99-custom-nvme.rules;
          sudo udevadm control --reload-rules && udevadm trigger;
          sudo ./script/setup_env.sh
          sudo cp config/ibofos_for_aws_vm_ci.conf /etc/pos/pos.conf
          sudo rmmod nvme_tcp
          sudo rmmod nvme_rdma
          sudo rmmod nvme_fabrics
          sudo modprobe nvme_tcp
          sudo modprobe nvme_rdma
          sudo modprobe nvme_fabrics

    - name: Normal IO Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/normal_io_npor_spor/normal_io.sh
        .github/workflows/script/normal_io_npor_spor/normal_io.sh ${{github.workspace}}

    - name: NPOR Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/normal_io_npor_spor/npor.sh
        .github/workflows/script/normal_io_npor_spor/npor.sh ${{github.workspace}}

    - name: SPOR Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/normal_io_npor_spor/spor_precommit.sh
        .github/workflows/script/normal_io_npor_spor/spor_precommit.sh ${{github.workspace}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Normal_IO_NPOR_SPOR_LOG
        path: |
          /var/log/pos

  Rebuild_SPOR_test:
    needs: Build
    runs-on: VM
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Test Setup
      working-directory: ${{github.workspace}}
      run: | 
        sudo script/pkgdep.sh
        sudo ./configure --with-fpic 
        cd lib; sudo cmake . -DSPDK_DEBUG_ENABLE=n -DUSE_LOCAL_REPO=n
        cd ${{github.workspace}}; sudo cp -f config/air_ci.cfg config/air.cfg
        sudo make CACHE=Y -j ${job_number} -C lib
        sudo mkdir bin
        sudo mkdir tool/cli/docs/manpage

    - name: Download POS Binaries
      uses: actions/download-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

    - name: change mode
      working-directory: ${{github.workspace}}
      run: |
          sudo chmod -R +x bin

    - name: POS setup
      working-directory: ${{github.workspace}}
      run: |
          sudo cp ./config/telemetry_default.yaml /etc/pos/telemetry_default.yaml;
          sudo install -m 755 bin/poseidonos /usr/local/bin
          sudo install -m 755 bin/poseidonos-cli /usr/local/bin
          sudo tool/udev/generate_udev_rule.sh
          sudo cp tool/udev/99-custom-nvme.rules /etc/udev/rules.d/99-custom-nvme.rules;
          sudo udevadm control --reload-rules && udevadm trigger;
          sudo ./script/setup_env.sh
          sudo cp config/ibofos_for_aws_vm_ci.conf /etc/pos/pos.conf
          sudo rmmod nvme_tcp
          sudo rmmod nvme_rdma
          sudo rmmod nvme_fabrics
          sudo modprobe nvme_tcp
          sudo modprobe nvme_rdma
          sudo modprobe nvme_fabrics

    - name: Rebuild SPOR Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/rebuild_spor/rebuild_spor.sh
        .github/workflows/script/rebuild_spor/rebuild_spor.sh ${{github.workspace}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Rebuild_SPOR_LOG
        path: |
          /var/log/pos


  Rebuild_Test:
    needs: Build
    runs-on: VM
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Test Setup
      working-directory: ${{github.workspace}}
      run: | 
        sudo script/pkgdep.sh
        sudo ./configure --with-fpic 
        cd lib; sudo cmake . -DSPDK_DEBUG_ENABLE=n -DUSE_LOCAL_REPO=n
        cd ${{github.workspace}}; sudo cp -f config/air_ci.cfg config/air.cfg
        sudo make CACHE=Y -j ${job_number} -C lib
        sudo mkdir bin
        sudo mkdir tool/cli/docs/manpage

    - name: Download POS Binaries
      uses: actions/download-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

    - name: change mode
      working-directory: ${{github.workspace}}
      run: |
          sudo chmod -R +x bin

    - name: POS setup
      working-directory: ${{github.workspace}}
      run: |
          sudo cp ./config/telemetry_default.yaml /etc/pos/telemetry_default.yaml;
          sudo install -m 755 bin/poseidonos /usr/local/bin
          sudo install -m 755 bin/poseidonos-cli /usr/local/bin
          sudo tool/udev/generate_udev_rule.sh
          sudo cp tool/udev/99-custom-nvme.rules /etc/udev/rules.d/99-custom-nvme.rules;
          sudo udevadm control --reload-rules && udevadm trigger;
          sudo ./script/setup_env.sh
          sudo cp config/ibofos_for_aws_vm_ci.conf /etc/pos/pos.conf
          sudo rmmod nvme_tcp
          sudo rmmod nvme_rdma
          sudo rmmod nvme_fabrics
          sudo modprobe nvme_tcp
          sudo modprobe nvme_rdma
          sudo modprobe nvme_fabrics

    - name: Rebuild Test 
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/rebuild/rebuild.sh
        .github/workflows/script/rebuild/rebuild.sh ${{github.workspace}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Rebuild_LOG
        path: |
          /var/log/pos


  Rotational_Rebuild_Test:
    needs: Build
    runs-on: VM
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Test Setup
      working-directory: ${{github.workspace}}
      run: | 
        sudo script/pkgdep.sh
        sudo ./configure --with-fpic 
        cd lib; sudo cmake . -DSPDK_DEBUG_ENABLE=n -DUSE_LOCAL_REPO=n
        cd ${{github.workspace}}; sudo cp -f config/air_ci.cfg config/air.cfg
        sudo make CACHE=Y -j ${job_number} -C lib
        sudo mkdir bin
        sudo mkdir tool/cli/docs/manpage

    - name: Download POS Binaries
      uses: actions/download-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

    - name: change mode
      working-directory: ${{github.workspace}}
      run: |
          sudo chmod -R +x bin

    - name: POS setup
      working-directory: ${{github.workspace}}
      run: |
          sudo cp ./config/telemetry_default.yaml /etc/pos/telemetry_default.yaml;
          sudo install -m 755 bin/poseidonos /usr/local/bin
          sudo install -m 755 bin/poseidonos-cli /usr/local/bin
          sudo tool/udev/generate_udev_rule.sh
          sudo cp tool/udev/99-custom-nvme.rules /etc/udev/rules.d/99-custom-nvme.rules;
          sudo udevadm control --reload-rules && udevadm trigger;
          sudo ./script/setup_env.sh
          sudo cp config/ibofos_for_aws_vm_ci.conf /etc/pos/pos.conf
          sudo rmmod nvme_tcp
          sudo rmmod nvme_rdma
          sudo rmmod nvme_fabrics
          sudo modprobe nvme_tcp
          sudo modprobe nvme_rdma
          sudo modprobe nvme_fabrics

    - name: Rotational Rebuild Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/rotational_rebuild/rotational_rebuild.sh
        .github/workflows/script/rotational_rebuild/rotational_rebuild.sh ${{github.workspace}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Rotational_Rebuild_LOG
        path: |
          /var/log/pos

  Unit_Test:
    needs: Build
    runs-on: VM
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Test Setup
      working-directory: ${{github.workspace}}
      run: | 
        sudo script/pkgdep.sh
        sudo ./configure --with-fpic 
        cd lib; sudo cmake . -DSPDK_DEBUG_ENABLE=n -DUSE_LOCAL_REPO=n
        cd ${{github.workspace}}; sudo cp -f config/air_ci.cfg config/air.cfg
        sudo make CACHE=Y -j ${job_number} -C lib
        sudo mkdir bin
        sudo mkdir tool/cli/docs/manpage

    - name: Download POS Binaries
      uses: actions/download-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

    - name: change mode
      working-directory: ${{github.workspace}}
      run: |
          sudo chmod -R +x bin

    - name: POS setup
      working-directory: ${{github.workspace}}
      run: |
          sudo cp ./config/telemetry_default.yaml /etc/pos/telemetry_default.yaml;
          sudo install -m 755 bin/poseidonos /usr/local/bin
          sudo install -m 755 bin/poseidonos-cli /usr/local/bin
          sudo tool/udev/generate_udev_rule.sh
          sudo cp tool/udev/99-custom-nvme.rules /etc/udev/rules.d/99-custom-nvme.rules;
          sudo udevadm control --reload-rules && udevadm trigger;
          sudo ./script/setup_env.sh
          sudo cp config/ibofos_for_aws_vm_ci.conf /etc/pos/pos.conf
          sudo rmmod nvme_tcp
          sudo rmmod nvme_rdma
          sudo rmmod nvme_fabrics
          sudo modprobe nvme_tcp
          sudo modprobe nvme_rdma
          sudo modprobe nvme_fabrics

    # Need separation building from running
    - name: UT Build and Run
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/ut_build_run_precommit.sh
        .github/workflows/script/unit/ut_build_run_precommit.sh ${{github.workspace}}

    - name: Copy UT Result to CI Server
      if: always()
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/unit/copy_ut_result.sh
        .github/workflows/script/unit/copy_ut_result.sh ${{github.workspace}} ${{github.sha}}

    - uses: mikepenz/action-junit-report@v2
      if: always() 
      with:
        report_paths: 'UnitTestResult/*.xml'

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Unit_LOG
        path: |
          /var/log/pos

  Volume_Test:
    needs: Build
    runs-on: VM
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Test Setup
      working-directory: ${{github.workspace}}
      run: | 
        sudo script/pkgdep.sh
        sudo ./configure --with-fpic 
        cd lib; sudo cmake . -DSPDK_DEBUG_ENABLE=n -DUSE_LOCAL_REPO=n
        cd ${{github.workspace}}; sudo cp -f config/air_ci.cfg config/air.cfg
        sudo make CACHE=Y -j ${job_number} -C lib
        sudo mkdir bin
        sudo mkdir tool/cli/docs/manpage

    - name: Download POS Binaries
      uses: actions/download-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

    - name: change mode
      working-directory: ${{github.workspace}}
      run: |
          sudo chmod -R +x bin

    - name: POS setup
      working-directory: ${{github.workspace}}
      run: |
          sudo cp ./config/telemetry_default.yaml /etc/pos/telemetry_default.yaml;
          sudo install -m 755 bin/poseidonos /usr/local/bin
          sudo install -m 755 bin/poseidonos-cli /usr/local/bin
          sudo tool/udev/generate_udev_rule.sh
          sudo cp tool/udev/99-custom-nvme.rules /etc/udev/rules.d/99-custom-nvme.rules;
          sudo udevadm control --reload-rules && udevadm trigger;
          sudo ./script/setup_env.sh
          sudo cp config/ibofos_for_aws_vm_ci.conf /etc/pos/pos.conf
          sudo rmmod nvme_tcp
          sudo rmmod nvme_rdma
          sudo rmmod nvme_fabrics
          sudo modprobe nvme_tcp
          sudo modprobe nvme_rdma
          sudo modprobe nvme_fabrics

    - name: Volume Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/volume/volume.sh
        .github/workflows/script/volume/volume.sh ${{github.workspace}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Volume_LOG
        path: |
          /var/log/pos

  WBT_IO_ST:
    needs: Build
    runs-on: VM
    steps:

    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Test Setup
      working-directory: ${{github.workspace}}
      run: | 
        sudo script/pkgdep.sh
        sudo ./configure --with-fpic 
        cd lib; sudo cmake . -DSPDK_DEBUG_ENABLE=n -DUSE_LOCAL_REPO=n
        cd ${{github.workspace}}; sudo cp -f config/air_ci.cfg config/air.cfg
        sudo make CACHE=Y -j ${job_number} -C lib
        sudo mkdir bin
        sudo mkdir tool/cli/docs/manpage

    - name: Download POS Binaries
      uses: actions/download-artifact@v3
      with:
        name: POS-Binaries
        path: |
          ${{github.workspace}}/bin

    - name: change mode
      working-directory: ${{github.workspace}}
      run: |
          sudo chmod -R +x bin

    - name: POS setup
      working-directory: ${{github.workspace}}
      run: |
          sudo cp ./config/telemetry_default.yaml /etc/pos/telemetry_default.yaml;
          sudo install -m 755 bin/poseidonos /usr/local/bin
          sudo install -m 755 bin/poseidonos-cli /usr/local/bin
          sudo tool/udev/generate_udev_rule.sh
          sudo cp tool/udev/99-custom-nvme.rules /etc/udev/rules.d/99-custom-nvme.rules;
          sudo udevadm control --reload-rules && udevadm trigger;
          sudo ./script/setup_env.sh
          sudo cp config/ibofos_for_aws_vm_ci.conf /etc/pos/pos.conf
          sudo rmmod nvme_tcp
          sudo rmmod nvme_rdma
          sudo rmmod nvme_fabrics
          sudo modprobe nvme_tcp
          sudo modprobe nvme_rdma
          sudo modprobe nvme_fabrics

    - name: WBT Command Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/wb_io_st/wbt_command_pre.sh
        .github/workflows/script/wb_io_st/wbt_command_pre.sh ${{github.workspace}} 

    - name: IO System Level Test
      working-directory: ${{github.workspace}}
      run: |
        chmod +x .github/workflows/script/wb_io_st/io_system_level.sh
        .github/workflows/script/wb_io_st/io_system_level.sh ${{github.workspace}} ${{github.sha}}

    - name: Upload POS log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: WBT_IO_ST_LOG
        path: |
          /var/log/pos